# Generated by Django 5.1.3 on 2025-01-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('clergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_ordination', models.DateField()),
                ('parish_assigned', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='clergy_photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('permissions', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clergy')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_venue', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clergy')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(max_length=200)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('meeting_venue', models.CharField(max_length=300)),
                ('agenda', models.TextField()),
                ('minutes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(to='core.clergy')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('parish_id', models.AutoField(primary_key=True, serialize=False)),
                ('parish_name', models.CharField(max_length=200)),
                ('parish_location', models.CharField(max_length=300)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parish_priest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clergy')),
            ],
        ),
        migrations.CreateModel(
            name='MassSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('mass_time', models.TimeField()),
                ('mass_date', models.DateField()),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clergy')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
        ),
        migrations.CreateModel(
            name='Sacrament',
            fields=[
                ('sacrament_id', models.AutoField(primary_key=True, serialize=False)),
                ('sacrament_type', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=200)),
                ('sacrament_date', models.DateField()),
                ('sacrament_location', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clergy')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraccount')),
            ],
        ),
    ]
