# Generated by Django 5.1.3 on 2025-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergy',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clergy',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clergy',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clergy',
            name='parish_assigned',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clergy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clergy_photos/'),
        ),
    ]
