# Generated by Django 5.1.3 on 2025-01-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clergy_email_alter_clergy_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='venue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parish',
            name='parish_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parish',
            name='parish_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parish',
            name='parish_priest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clergy'),
        ),
    ]
