# Generated by Django 5.1.3 on 2025-01-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_venue_alter_parish_parish_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(max_length=255),
        ),
    ]
