# Generated by Django 5.1.3 on 2025-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_event_name_alter_event_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
